public class AccountOperations {
    public static Account setDefaultDescription(Account a) {        
         a.Description = 'Default Description o no';
         return a;
    }
    public static Account setDefaultPhone(Account a){ //Dev01
        a.Phone = '987654321 ========>'; 
        return a;
        //Comentarios que pasara??? ---
        // cc.subcripbnerwwwwwwwwwwwwwwwwwwwwww Line 154 ok XXXX
        // line to original will remove 155 original XXXX
        
        // line update ccsubcripber   157 original
        // line update recordid   158 original
        //Next Comments
        //Prueba del User3
    }
}
